on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-2019]
        node: [10, 12, 14]
        command: [git, curl]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: which ${{ matrix.command}}
      - run: whereis ${{ matrix.command}}
      - run: node test.js ${{ matrix.command}}
